# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract <- function(feature_table, boundary_coordinates, mini_image, class_label, max_number_of_frames, maximum_boundary_length, maximum_cell_area, cooccurrence_levels, number_of_wavelet_levels) {
    .Call('_CellPhe_extract', PACKAGE = 'CellPhe', feature_table, boundary_coordinates, mini_image, class_label, max_number_of_frames, maximum_boundary_length, maximum_cell_area, cooccurrence_levels, number_of_wavelet_levels)
}

