# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract Features
#'
#' @param feature_table TODO
#' @param boundary_coordinates TODO
#' @param mini_image TODO
#' @param class_label TODO
#' @param max_number_of_frames TODO
#' @param maximum_boundary_length TODO
#' @param maximum_cell_area TODO
#' @param cooccurrence_levels TODO
#' @param number_of_wavelet_levels TODO
#'
#' @return TODO
#'
#' @export
extract <- function(feature_table, boundary_coordinates, mini_image, class_label, max_number_of_frames, maximum_boundary_length, maximum_cell_area, cooccurrence_levels, number_of_wavelet_levels) {
    .Call(`_CellPhe_extract`, feature_table, boundary_coordinates, mini_image, class_label, max_number_of_frames, maximum_boundary_length, maximum_cell_area, cooccurrence_levels, number_of_wavelet_levels)
}

